//user reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_USER_LOCATION = 'SET_USER_LOCATION';
export const SET_USER_FILTER = 'SET_USER_FILTER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
//ui reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const VERIFYING_LOCATION = 'VERIFYING_LOCATION';
export const STOP_VERIFYING_LOCATION = 'STOP_VERIFYING_LOCATION';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const LOADING_DATA = 'LOADING_DATA';
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
//data reducer types
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const ADD_EVENT = 'ADD_EVENT';
export const SET_EVENT = 'SET_EVENT';
export const SET_USER_EVENTS = 'SET_USER_EVENTS';
export const SET_MEETING_POINT = 'SET_MEETING_POINT';
export const EVENT_ADDED = 'EVENT_ADDED';
